baseURL = 'https://alugatuci.org/'
locale = 'en-us'
title = 'Anteater Linux User Group'
theme = 'ananke'
disableKinds = ['taxonomy', 'term', 'RSS']
relativeURLs = true

[params]
site_logo = "images/alug-logo.png"
favicon = "images/ALUG@UCI_icon.png"

[params.ananke]
custom_css = ["custom.css"]
show_recent_posts = false

[[menu.main]]
name = "Projects"
url = "https://git.alugatuci.org/"