baseURL = 'https://alugatuci.org/'
locale = 'en-us'
title = 'Anteater Linux User Group'
theme = 'ananke'
disableKinds = ['taxonomy', 'term', 'RSS']
relativeURLs = true

[params]
site_logo = "images/alug-logo.png"
favicon = "images/ALUG@UCI_icon.png"

[params.ananke]
custom_css = ["custom.css"]
show_recent_posts = false

[[menu.main]]
name = "Get Involved"
url = "/contact/"
weight = 1

[[menu.main]]
name = "Git"
url = "https://git.alugatuci.org/"
weight = 2

[[menu.main]]
name = "About Us"
url = "/about/"
weight = 3

[[menu.main]]
name = "Contact Us"
url = "/contact/"
weight = 4
